### FORMATTING ###
[tool.ruff]
line-length     = 90
indent-width    = 2
target-version  = "py310"

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true


[tool.isort]
profile = "black"
line_length = 90
indent="  "

#### LINTING ####
[tool.basedpyright]
reportImplicitStringConcatenation = false
reportUnusedCallResult = false
pythonVersion = "3.10"
#stubPath = "typings"
#ignore = ["typings"]
